### ISSUE TITLE
ARM GPUs are now too detailed

### ISSUE THREAD

**Issue by philmmanjaro** [manjaro/mdd#10]
![image](https://github.com/user-attachments/assets/3f940b29-1c09-40b4-8718-9b9c3e271832)
With the current ARM support the gpu data of ARM SBCs are too detailed. Having just ARM as GPU type would be enough, cos graphic drivers are normally in the kernel already and not shipped with out-of-tree modules.

**Comment by iuncuim** [comment]
Welcome to MDD - The Manjaro Data Donor
...
    "graphics": {
        "comp": "kwin_wayland",
        "dri": "sun4i-drm",
        "gpus": [
            {
                "vendor": null,
                "model": "sun50i-h616-mali",
                "driver": "panfrost"
            },
            {
                "vendor": null,
                "model": "sun50i-h616-dw-hdmi",
                "driver": "sun8i_dw_hdmi"
            },
            {
                "vendor": null,
                "model": "sun50i-h6-display-engine",
                "driver": "sun4i_drm"
            }
        ],
        "outputs": [
            {
                "model": null,
                "res": null,
                "refresh": null,
                "dpi": null,
                "size": null,
                "mapped": "Unknown-1"
            }
        ]
    },
  ....

**Comment by romangg** [comment]
SQL query was adapted.
