### ISSUE TITLE
last_update is wrong

### ISSUE THREAD

**Issue by MR-Diamond** [manjaro/mdd#13]
mdd, on my system, reports last_update as 2022-04-15, but is not true: currently, the last update of my system, was on 2024-10-10.

**Comment by romangg** [comment]
What does `grep "\\[ALPM\\] upgraded" /var/log/pacman.log | tail -3` give you?

**Comment by MR-Diamond** [comment]
```
[2022-04-15T22:09:15+0200] [ALPM] upgraded libsoup3 (3.0.4-2 -> 3.0.6-1)
[2022-04-15T22:09:15+0200] [ALPM] upgraded tracker3 (3.2.1-2 -> 3.3.0-1)
[2022-04-15T22:09:15+0200] [ALPM] upgraded gtk-update-icon-cache (1:4.6.1-3 -> 1:4.6.2-1)
```

**Comment by MR-Diamond** [comment]
> If I run `grep -a`

I used grep with the -a flag because the first command alerts me about
> grep: /var/log/pacman.log: binary file matches

**Comment by romangg** [comment]
Interesting. I don't know what that means here regarding the file. Has the log been changed to use a binary format? In any case maybe it's then enough to add the `-a` flag to the call in MDD.

**Comment by MR-Diamond** [comment]
> Has the log been changed to use a binary format?

I never touched /var/log/pacman.log

**Comment by romangg** [comment]
The file might have been damaged at some point in the past, like [this StackOverflow comment](https://stackoverflow.com/questions/23512852/grep-binary-file-matches-how-to-get-normal-grep-output#comment130312987_23512981) implies. For example by an incomplete file write or so.
